### ISSUE TITLE
Sometimes it gives me a timeout in Amazon EC2 + Elasticache

### ISSUE THREAD

**Issue by zaguiini** [memcachier/memjs#103]
Trying to create the client hosted on an EC2 instance, with the Redis instance up on Elasticache.

This is what I get: `MemJS: Server <elasticache.endpoint:port> failed after (2) retries with error - socket timed out waiting on response.`

I'm instanciating the Client like this:

```javascript
Client.create('elasticache.endpoint:port')
```

This URL is my Elasticache URL, and sometimes it gives this timeout, sometimes it does not. I'm more like a front-end developer, so I'm kind of newbie with devops.

The security group allows all inbound and outbound traffic.

Can someone explain me why it throws this error? (Note: it sometimes makes the page loading significantly slower...)

**Comment by alevy** [comment]
Redis is a different server and protocol from memcache, even though the Amazon product name "ElastiCache" is used for both services. I think you'll need to either use memcache on the server or use a Redis client library.
