### ISSUE TITLE
TLS support for memjs

### ISSUE THREAD

**Issue by Khalian** [memcachier/memjs#169]
https://stackoverflow.com/questions/75154040/question-about-setting-up-a-node-js-client-into-elasticache-memcached-cluster-wi

Specifically to support https://aws.amazon.com/about-aws/whats-new/2022/05/amazon-elasticache-memcached-supports-encryption-data-transit/

**Comment by msanandrea** [comment]
Any updates on this? Or do I have to migrate to `memcache-client` ?

**Comment by saschat** [comment]
Unfortunately, we don't have the capacity to implement this feature. PRs are welcome, though.
